version: '3.8'

# Minimal-Setup für Netzwerk-Probleme
services:
  mongodb:
    image: mongo:4.4
    container_name: ipad_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ipad_admin_2024
      MONGO_INITDB_DATABASE: iPadDatabase
    volumes:
      - mongodb_data:/data/db
    ports:
      - "0.0.0.0:27017:27017"
    networks:
      - ipad_network
    command: mongod --auth --bind_ip_all

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ipad_backend
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://admin:ipad_admin_2024@mongodb:27017/iPadDatabase?authSource=admin
      - SECRET_KEY=your-super-secret-key-change-this-in-production
      - IPAD_DB_NAME=iPadDatabase
    volumes:
      - backend_uploads:/app/uploads
    ports:
      - "0.0.0.0:8001:8001"
    depends_on:
      - mongodb
    networks:
      - ipad_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.minimal
      args:
        - REACT_APP_BACKEND_URL=/api
    container_name: ipad_frontend_build
    volumes:
      - frontend_build:/app/build
    networks:
      - ipad_network

  nginx:
    image: nginx:alpine
    container_name: ipad_nginx
    restart: unless-stopped
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - frontend_build:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
    networks:
      - ipad_network

volumes:
  mongodb_data:
  backend_uploads:
  frontend_build:

networks:
  ipad_network:
    driver: bridge